apiVersion: mixapp.easystack.io/v1
kind: VirtualMachine
metadata:
  name: test-app-2535ffda6f48477e98d6a1e6b5a19288
spec:
  # Add fields here
  project:
    projectID: "2535ffda6f48477e98d6a1e6b5a19288"
  server:
    replicas: 1
    name_prefix: "test-app"
    image: "11c9463b-43dd-4701-8942-3ea1ba22ff3f"
    flavor: "1-512-20"
    availability_zone: "nova"
    admin_pass: "passw0rd"
    boot_volume_type: "hdd"
    boot_volume_size: "20G"
    security_group: "default"
  network:
    external_network: "public_net"
    private_network_cidr: "192.168.18.0/24"
    private_network_name: "ecns-private"
  assemblyPhase: "Creating"
